### ISSUE TITLE
group the clusters per jet and not per event

### ISSUE THREAD

**Issue by jmsardain** [jmsardain/pumitigation#1]
We need to group the clusters per jet and not per event. it should be done using:
df.groupby('jetCnt') and then getting the info like this
`grouped = df.groupby('jetCnt')
for group_name, group_data in grouped:
     print(group_data['clusterE'].tolist())
`

**Comment by andreyvinasco** [comment]
Look at my branch @jmsardain , I change the way is created the dataset. Basically I copy and paste my previous code and I save the graphs dataset. The graphs can be modified before training (see modify_graphs() function in train.py) in case you want to remove some node reatures or modify/add some variables.

**Comment by jmsardain** [comment]
this is now done correctly
